### ISSUE TITLE
ClassNotFoundException: com.otaliastudios.firestore.FirestoreMapMetadataImpl

### ISSUE THREAD

**Issue by DanielAsher** [natario1/Firestore#11]
Hi, 

thanks for this great project. It makes firestore so much nicer to work with.

I'm getting a `java.lang.ClassNotFoundException: com.otaliastudios.firestore.FirestoreMapMetadataImpl` error occasionally and I've searched the source and kapt generated files but couldn't find any such file or class.

Here is a summary stack trace:
```
java.lang.ClassNotFoundException: com.otaliastudios.firestore.FirestoreMapMetadataImpl
	 at java.lang.Class.classForName(Native Method)
	 at java.lang.Class.forName(Class.java:453)
	 at java.lang.Class.forName(Class.java:378)
	 at com.otaliastudios.firestore.FirestoreDocument$Companion.metadataProvider$firestore_release(FirestoreDocument.kt:5)
	 at com.otaliastudios.firestore.FirestoreMap.set(FirestoreMap.kt:9)
	 at com.otaliastudios.firestore.FirestoreMap.set(FirestoreMap.kt:6)
```

Should this class be found, or is this a client-side coding error?

Cheers,

Daniel

**Comment by natario1** [comment]
It should definitely be found. However, if it was totally missing, you'd get this error very frequently. Not sure what's going on.

Does this maybe happen only on builds with proguard on?

**Comment by DanielAsher** [comment]
Hi Mattia,

thanks for the speedy response. Much appreciated.

This issue seems to affect debug builds.

Once the build has succeeded I'm unable to find the file `FirestoreMapMetadataImpl.kt` in our 
`app/build/generated/source/kapt/stagingDebug/com/otaliastudios/firestore` folder with only the `BR.java` file present

I built the demo project, and I also can't find `FirestoreMapMetadataImpl.kt` in
`demo/build/generated/source/kapt/debug/com/otalistudios/firestore/demo`

<img width="386" alt="otaliastudios firestore kapt generated classes" src="https://user-images.githubusercontent.com/7915553/83153747-3aacf080-a0f7-11ea-974e-e5148ff03c68.png">

I noticed that [demo/proguard-rules.pro](https://github.com/natario1/Firestore/blob/master/demo/proguard-rules.pro) do not contain any rules.

It would be great to get to the bottom of this issue, and perhaps include some advice on proguard in the README. Should the `*MetadataImpl` files be added to proguard?

Very much appreciate any help, as we'd love to use this library!

**Comment by natario1** [comment]
Could you share the model class that you are using? The @FirestoreClass that's causing this issue. Or if you don't know which one, you can post all of them. I am thinking that maybe we don't currently support the way you're using it.

**Comment by DanielAsher** [comment]
I'm dynamically creating some properties. This seems to work fine, mostly e.g.` this[newSessionIndexKey] = newSession`

It would be great to understand whether `FirestoreMapMetadataImpl` should be created by the kapt annotation processor, and therefore whether the error is spurious, or correct.

The error is created at `com.nusic.mashup.service.firebase.User$SessionHistory.add`

I doubt this, but I thought I'd ask whether using the optional generic type `FirestoreMap<Any?>` and `FirestoreMap<Event?>` instead of `FirestoreMap<Any>` and `FirestoreMap<Event>` could cause this?

```kotlin
    @FirestoreClass
    class EventHistory : FirestoreMap<Any>() {

        var lastEventOrdinal: Int by this

        init {
            lastEventOrdinal = 0
        }

        fun add(event: Event, user: User) {
            val now = Timestamp.now()
            if (user.lastSessionEnd.seconds + 600 < now.seconds) {
                createNewSessionAndAdd(event, user, now)
            }
            else {
                val sessionIndexKey = getSessionIndexKey(user.lastSessionIndex, user.lastSessionStart)
                when (val session = this[sessionIndexKey] as? SessionHistory) {
                    null    -> {
                        createNewSessionAndAdd(event, user, now)
                    }
                    session -> {
                        user.lastSessionEnd = now
                        lastEventOrdinal += 1
                        session.add(event, lastEventOrdinal)
                    }
                }
            }
        }

        private fun createNewSessionAndAdd(event: Event,
                                           user: User,
                                           now: Timestamp) {
            val newSession = SessionHistory()
            lastEventOrdinal = 0
            newSession.add(event, 0)
            user.lastSessionStart = now
            user.lastSessionEnd = now
            user.lastSessionIndex += 1
            val newSessionIndexKey = getSessionIndexKey(user.lastSessionIndex, now)
            this[newSessionIndexKey] = newSession
        }

        private fun getSessionIndexKey(sessionIndex: Int, timestamp: Timestamp): String {
            val sessionIndexString = "$sessionIndex".padStart(4, '0')
            val dateTime = SimpleDateFormat.getDateTimeInstance().format(timestamp.toDate())
            return "Session $sessionIndexString - $dateTime"
        }
    }
    @FirestoreClass
    class SessionHistory : FirestoreMap<Event>() {
        fun add(event: Event, eventOrdinal: Int) {
            val time = SimpleDateFormat.getTimeInstance().format(Date())
            val eventKey = "${"$eventOrdinal".padStart(4, '0')}: ${event.kind} - $time"
            this[eventKey] = event
        }
    }
```

**Comment by natario1** [comment]
> It would be great to understand whether FirestoreMapMetadataImpl should be created by the kapt annotation processor, and therefore whether the error is spurious, or correct.

I was wrong saying that it should be created. It should not, so if it isn't, that's correct.

> I'd ask whether using the optional generic type FirestoreMap<Any?> and FirestoreMap<Event?> instead of FirestoreMap<Any> and FirestoreMap<Event> could cause this?

It shouldn't make any difference. Does the error appear any time you call add()? The demo app model has a similar structure, but it doesn't seem to show this issue.

**Comment by DanielAsher** [comment]
The error occurs only on some user devices/os so it's hard to nail down.

I'll try to share more insights as the crashes come in.

**Comment by natario1** [comment]
@DanielAsher do you have more information by any chance?

**Comment by DanielAsher** [comment]
I think this commit: https://github.com/natario1/Firestore/pull/17/commits/c1f2d3d23a4d0382a111b85106a0dba58aaec328 in this PR https://github.com/natario1/Firestore/pull/17 fixes the issue
