### ISSUE TITLE
app:kaptStagingDebugKotlin [WARN] Expected 1 originating source file but detected 0

### ISSUE THREAD

**Issue by DanielAsher** [natario1/Firestore#14]
When running a build with the `Firestore` kapt processor the following warning is generated:

```
> Task :app:kaptStagingDebugKotlin [WARN] Issue detected with com.otaliastudios.firestore.compiler.Processor. Expected 1 originating source file when generating /Users/.../firebase/UserMetadataImpl.kt, but detected 0: [].
```

Any insight into this warning would be useful.

Thanks!

**Comment by natario1** [comment]
I think it happens when you use kapt() in a module (like "app") but the User class is in another module which app depends on. If so, try to use kapt() in the base module as well

**Comment by DanielAsher** [comment]
@natario1  Thanks for your speedy response!!

Our project (unfortunately for us!) has a single module, so this cannot be the issue.

**Comment by natario1** [comment]
I'll take a look!

**Comment by DanielAsher** [comment]
I've verified that this warning is also issued in the `demo` project

**Comment by DanielAsher** [comment]
Unfulfilled
