### ISSUE TITLE
Bug: @Exclude not respected in v0.6.0 and v0.7.0

### ISSUE THREAD

**Issue by DanielAsher** [natario1/Firestore#15]
Hi,

I'm trying to add a property that is not part of the firestore document, but neither:
* adding a raw property (without delegation `by this`)
* using `@Exclude`

is working to exclude the property from the generated `MetadataImpl` class.

This can be easily verified by adding a property to the `demo` `User` class:
```kotlin
@Exclude var ignored: Boolean = true
```
which generates:
```diff
class UserMetadataImpl : FirestoreMetadata {
  override fun <T> create(key: String): T? = when (key) {
    "createdAt" -> com.google.firebase.Timestamp(0L, 0) as T
    "updatedAt" -> com.google.firebase.Timestamp(0L, 0) as T
+   "ignored" -> false as T
    "imageUrl" -> "" as T
    "messages" ->
        com.otalistudios.firestore.demo.User.Messages::class.java.getConstructor().newInstance() as
        T
    "type" -> 0 as T
    else -> null
  }
```

it look like [this](https://github.com/natario1/Firestore/blob/c5150aee33a0981a6f273aff6a8537cfac904745/compiler/src/main/kotlin/com/otaliastudios/firestore/compiler/Processor.kt#L70) call to kotlinPoet is not populating the annotations correctly as they are alway empty.

As the `@Exclude` annotation fails to compile when attached to a delegated property:
```kotlin
 @Exclude var ignored: Boolean by this 
```
causes compile error:
```diff
- Error: This annotation is not applicable to target 'member property with delegate'
```

I'm not sure of the utility of using `@Exclude`

I've noticed and corrected that you are filtering by `it.delegated` on `master`

Would you be able to release this a.s.a.p as I cannot easily continue without being able to exclude a class property at the moment.

Cheers,

Daniel

**Comment by natario1** [comment]
I think it should be applied to the getter, with `@get:Exclude`

**Comment by DanielAsher** [comment]
This is also ignored.

Adding to `User.kt:16`:
```kotlin
    @get:Exclude var ignored: Boolean by this
```
to `Processor.kt:72`:
```kotlin
    logInfo("Inspecting property ${property.name} with annotations(${property.annotations})of type ${property.type}.")
```

The processor logs:
```
Note: Inspecting property ignored with annotations([])of type kotlin.Boolean.
```

and `UserMetadataImpl.kt:18` is:
```kotlin
 "ignored" -> false as T
```

**Comment by DanielAsher** [comment]
Unfulfilled
