### ISSUE TITLE
Cannot implement methods listed in ReadME ?

### ISSUE THREAD

**Issue by JobGetabu** [natario1/Firestore#6]
> The document class exposes delete(), save() and trySave() methods. They all return a Task<?> object from the Google gms library, which you should be used to. This lets you add success and failure callbacks, as well as chain operations with complex dependencies.

**Comment by natario1** [comment]
What's your problem?

**Comment by JobGetabu** [comment]
Fixing first #4  will auto fix this one, sorry
https://github.com/natario1/Firestore/issues/4#issuecomment-598590845
